### PR TITLE
Visual Studio compilation fixes

### PR DESCRIPTION
**Pull request by Yitzi2**

### CODE REVIEW

**Comment by mkeeter** [comment]
Thanks!

**Comment by omgitsraven** [comment]
So wait, does this mean that Windows compilation should actually fully work, or is this just some fixes among the larger list?

**Comment by omgitsraven** [comment]
(Seemingly not, I'm still getting errors on building the solution.)

**Comment by mkeeter** [comment]
@omgitsraven Want to post them here?  @Yitzi2 is building libfive into a larger application, so they're using their own CMake files, but maybe he could offer some tips.

**Pull request merged**
