### PR TITLE
Move Guile bindings into pure Scheme

### LINKED ISSUE #380: Studio can't be double-clicked on Ubuntu
### Description

After building on Ubuntu, the Studio file that results just has a generic 'text document' icon, and double-clicking it produces the following error:
image

It can still be run from the command line, but older versions of Studio didn't require this workaround, so it would be nice to fix if possible.

### Versions

- Operating system: Ubuntu 18.04.5 LTS
- `libfive` commit hash: 30203ffd710101c7811283e14f16a975b15c2dd7
  - Is this the latest commit to `master`?  yes
- Qt version (if applicable): 5.9.5

### Additional Information

It's quite possible that this isn't a change in the Studio *source*, but rather a change in my build process, which has had to deviate significantly from the recommended one in order to successfully build the latest version (which I plan on bringing up as a separate issue once this is resolved...)

I've seen threads online that suggest that this issue can be related to Qt (which is one of the changes I made to the build process; letting the Qt version be implied rather than specifying it manually) but I'm in over my head enough not to be sure how to move forward with this (I barely got it building again at all...)

For reference, here is my current build process:
```
export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig
cmake -DCMAKE_C_COMPILER=gcc-7 -DCMAKE_CXX_COMPILER=g++-7 ..
make -j4
```
I'm open to any suggested changes at this point.

### PR DESCRIPTION
**Pull request by mkeeter**
This PR removes the `libfive-guile.dylib` shared library in favor of pure Guile bindings to `libfive.dylib`, using Guile's FFI to call C functions.  This should have no user-visible impacts, but is important for future plans: soon, we'll be doing something similar with `libfive-stdlib.dylib`, the upcoming canonical standard library.

`make install` is updated to install the `(libfive ...)` module source files to Guile's `(%site-dir)` directory.  This addresses #336 and #337 – @KoviRobi, want to see if this suits your use case?

With the newly improved `make install` command, I'm going to start recommending that on Linux (instead of running from the `build` directory).

To make life easier, I've added a [`Studio.desktop`](https://github.com/libfive/libfive/blob/pure-scheme-bindings/studio/deploy/linux/Studio.desktop) file for Linux users.  This should theoretically let you double-click to launch, though I don't have a Linux system to test on.

The combination of `make install` and `Studio.desktop` should fix #380 – @omgitsraven , want to take a look?

(I also updated the Mac `deploy.sh` script, because it broke when I left it alone for three years)

### CODE REVIEW

**Comment by omgitsraven** [comment]
1. it needed to be `sudo make install`, doing it without sudo gave an error
2. I didn't see anything change after running `sudo make install`? Where should I be looking to find this "installed" version? Here's the output, if it helps:
```
hazel@hazel-VirtualBox:~/stuff/libfive/libfive/build$ sudo make install
[sudo] password for hazel: 
[  0%] Built target five-version
[ 53%] Built target five
[ 54%] Built target five-stdlib
[ 82%] Built target libfive-test
[ 83%] Automatic MOC and UIC for target Studio
[ 83%] Built target Studio_autogen
[100%] Built target Studio
Install the project...
-- Install configuration: "RELEASE"
-- Installing: /usr/local/lib/pkgconfig/libfive.pc
-- Installing: /usr/local/lib/libfive.so
-- Installing: /usr/local/include/libfive.h
-- Installing: /usr/local/include/libfive
-- Installing: /usr/local/include/libfive/render
-- Installing: /usr/local/include/libfive/render/axes.hpp
-- Installing: /usr/local/include/libfive/render/brep
-- Installing: /usr/local/include/libfive/render/brep/dual.hpp
-- Installing: /usr/local/include/libfive/render/brep/simplex
-- Installing: /usr/local/include/libfive/render/brep/simplex/simplex_mesher.hpp
-- Installing: /usr/local/include/libfive/render/brep/simplex/simplex_worker_pool.hpp
-- Installing: /usr/local/include/libfive/render/brep/simplex/qef.hpp
-- Installing: /usr/local/include/libfive/render/brep/simplex/simplex_debug.hpp
-- Installing: /usr/local/include/libfive/render/brep/simplex/simplex_tree.hpp
-- Installing: /usr/local/include/libfive/render/brep/simplex/simplex_neighbors.hpp
-- Installing: /usr/local/include/libfive/render/brep/simplex/surface_edge_map.hpp
-- Installing: /usr/local/include/libfive/render/brep/per_thread_brep.hpp
-- Installing: /usr/local/include/libfive/render/brep/neighbor_tables.hpp
-- Installing: /usr/local/include/libfive/render/brep/brep.hpp
-- Installing: /usr/local/include/libfive/render/brep/object_pool.hpp
-- Installing: /usr/local/include/libfive/render/brep/util.hpp
-- Installing: /usr/local/include/libfive/render/brep/edge_tables.hpp
-- Installing: /usr/local/include/libfive/render/brep/free_thread_handler.hpp
-- Installing: /usr/local/include/libfive/render/brep/vol
-- Installing: /usr/local/include/libfive/render/brep/vol/vol_worker_pool.hpp
-- Installing: /usr/local/include/libfive/render/brep/vol/vol_neighbors.hpp
-- Installing: /usr/local/include/libfive/render/brep/vol/vol_tree.hpp
-- Installing: /usr/local/include/libfive/render/brep/hybrid
-- Installing: /usr/local/include/libfive/render/brep/hybrid/hybrid_worker_pool.hpp
-- Installing: /usr/local/include/libfive/render/brep/hybrid/hybrid_tree.hpp
-- Installing: /usr/local/include/libfive/render/brep/hybrid/hybrid_debug.hpp
-- Installing: /usr/local/include/libfive/render/brep/hybrid/hybrid_mesher.hpp
-- Installing: /usr/local/include/libfive/render/brep/hybrid/hybrid_neighbors.hpp
-- Installing: /usr/local/include/libfive/render/brep/default_new_delete.hpp
-- Installing: /usr/local/include/libfive/render/brep/indexes.hpp
-- Installing: /usr/local/include/libfive/render/brep/mesh.hpp
-- Installing: /usr/local/include/libfive/render/brep/settings.hpp
-- Installing: /usr/local/include/libfive/render/brep/manifold_tables.hpp
-- Installing: /usr/local/include/libfive/render/brep/xtree.hpp
-- Installing: /usr/local/include/libfive/render/brep/root.hpp
-- Installing: /usr/local/include/libfive/render/brep/worker_pool.hpp
-- Installing: /usr/local/include/libfive/render/brep/region.hpp
-- Installing: /usr/local/include/libfive/render/brep/dc
-- Installing: /usr/local/include/libfive/render/brep/dc/dc_contourer.hpp
-- Installing: /usr/local/include/libfive/render/brep/dc/dc_worker_pool.hpp
-- Installing: /usr/local/include/libfive/render/brep/dc/dc_mesher.hpp
-- Installing: /usr/local/include/libfive/render/brep/dc/dc_tree.hpp
-- Installing: /usr/local/include/libfive/render/brep/dc/dc_neighbors.hpp
-- Installing: /usr/local/include/libfive/render/brep/dc/dc_flags.hpp
-- Installing: /usr/local/include/libfive/render/brep/dc/intersection.hpp
-- Installing: /usr/local/include/libfive/render/brep/dc/marching.hpp
-- Installing: /usr/local/include/libfive/render/brep/progress.hpp
-- Installing: /usr/local/include/libfive/render/brep/contours.hpp
-- Installing: /usr/local/include/libfive/render/brep/neighbors.hpp
-- Installing: /usr/local/include/libfive/render/discrete
-- Installing: /usr/local/include/libfive/render/discrete/voxels.hpp
-- Installing: /usr/local/include/libfive/render/discrete/heightmap.hpp
-- Installing: /usr/local/include/libfive/solve
-- Installing: /usr/local/include/libfive/solve/solver.hpp
-- Installing: /usr/local/include/libfive/eval
-- Installing: /usr/local/include/libfive/eval/base.hpp
-- Installing: /usr/local/include/libfive/eval/eval_interval.hpp
-- Installing: /usr/local/include/libfive/eval/eval_jacobian.hpp
-- Installing: /usr/local/include/libfive/eval/clause.hpp
-- Installing: /usr/local/include/libfive/eval/deck.hpp
-- Installing: /usr/local/include/libfive/eval/tape.hpp
-- Installing: /usr/local/include/libfive/eval/eval_array_size.hpp
-- Installing: /usr/local/include/libfive/eval/interval.hpp
-- Installing: /usr/local/include/libfive/eval/eval_deriv_array.hpp
-- Installing: /usr/local/include/libfive/eval/eval_array.hpp
-- Installing: /usr/local/include/libfive/eval/eval_feature.hpp
-- Installing: /usr/local/include/libfive/eval/evaluator.hpp
-- Installing: /usr/local/include/libfive/eval/feature.hpp
-- Installing: /usr/local/include/libfive/tree
-- Installing: /usr/local/include/libfive/tree/key.hpp
-- Installing: /usr/local/include/libfive/tree/serializer.hpp
-- Installing: /usr/local/include/libfive/tree/tree.hpp
-- Installing: /usr/local/include/libfive/tree/archive.hpp
-- Installing: /usr/local/include/libfive/tree/deserializer.hpp
-- Installing: /usr/local/include/libfive/tree/opcode.hpp
-- Installing: /usr/local/include/libfive/tree/operations.hpp
-- Installing: /usr/local/include/libfive/tree/data.hpp
-- Installing: /usr/local/include/libfive/oracle
-- Installing: /usr/local/include/libfive/oracle/oracle_clause.hpp
-- Installing: /usr/local/include/libfive/oracle/oracle.hpp
-- Installing: /usr/local/include/libfive/oracle/oracle_storage.hpp
-- Installing: /usr/local/include/libfive/oracle/transformed_oracle.hpp
-- Installing: /usr/local/include/libfive/oracle/oracle_context.hpp
-- Installing: /usr/local/include/libfive/oracle/transformed_oracle_clause.hpp
-- Installing: /usr/share/guile/site/2.2/libfive
-- Installing: /usr/share/guile/site/2.2/libfive/util.scm
-- Installing: /usr/share/guile/site/2.2/libfive/lib.scm
-- Installing: /usr/share/guile/site/2.2/libfive/sandbox.scm
-- Installing: /usr/share/guile/site/2.2/libfive/stdlib
-- Installing: /usr/share/guile/site/2.2/libfive/stdlib/shapes.scm
-- Installing: /usr/share/guile/site/2.2/libfive/stdlib/transforms.scm
-- Installing: /usr/share/guile/site/2.2/libfive/stdlib/csg.scm
-- Installing: /usr/share/guile/site/2.2/libfive/stdlib/text.scm
-- Installing: /usr/share/guile/site/2.2/libfive/vec.scm
-- Installing: /usr/share/guile/site/2.2/libfive/kernel.scm
-- Installing: /usr/local/bin/Studio
-- Set runtime path of "/usr/local/bin/Studio" to ""
```
3. Studio launched, but it crashed very quickly; here's what it wrote to the terminal:
```
hazel@hazel-VirtualBox:~/stuff/libfive/libfive/build/studio$ ./Studio
;;; note: auto-compilation is enabled, set GUILE_AUTO_COMPILE=0
;;;       or pass the --no-auto-compile argument to disable.
;;; compiling /usr/share/guile/site/2.2/libfive/kernel.scm
;;; compiling /usr/share/guile/site/2.2/libfive/lib.scm
;;; libfive/lib.scm:27:2: warning: possibly unbound variable `with-exception-handler'
;;; compiled /home/hazel/.cache/guile/ccache/2.2-LE-8-3.A/usr/share/guile/site/2.2/libfive/lib.scm.go
;;; WARNING: compilation of /usr/share/guile/site/2.2/libfive/kernel.scm failed:
;;; In procedure module-lookup: Unbound variable: with-exception-handler
;;; compiling /usr/share/guile/site/2.2/libfive/vec.scm
;;; compiled /home/hazel/.cache/guile/ccache/2.2-LE-8-3.A/usr/share/guile/site/2.2/libfive/vec.scm.go
;;; compiling /usr/share/guile/site/2.2/libfive/sandbox.scm
;;; compiled /home/hazel/.cache/guile/ccache/2.2-LE-8-3.A/usr/share/guile/site/2.2/libfive/sandbox.scm.go
;;; compiling /usr/share/guile/site/2.2/libfive/stdlib/shapes.scm
;;; compiling /usr/share/guile/site/2.2/libfive/stdlib/csg.scm
;;; compiling /usr/share/guile/site/2.2/libfive/util.scm
;;; compiled /home/hazel/.cache/guile/ccache/2.2-LE-8-3.A/usr/share/guile/site/2.2/libfive/util.scm.go
;;; compiled /home/hazel/.cache/guile/ccache/2.2-LE-8-3.A/usr/share/guile/site/2.2/libfive/stdlib/csg.scm.go
;;; compiling /usr/share/guile/site/2.2/libfive/stdlib/transforms.scm
;;; compiled /home/hazel/.cache/guile/ccache/2.2-LE-8-3.A/usr/share/guile/site/2.2/libfive/stdlib/transforms.scm.go
;;; compiled /home/hazel/.cache/guile/ccache/2.2-LE-8-3.A/usr/share/guile/site/2.2/libfive/stdlib/shapes.scm.go
;;; compiling /usr/share/guile/site/2.2/libfive/stdlib/text.scm
;;; compiled /home/hazel/.cache/guile/ccache/2.2-LE-8-3.A/usr/share/guile/site/2.2/libfive/stdlib/text.scm.go
guile: uncaught throw to unbound-variable: (#f Unbound variable: ~S (libfive-opcode-enum) #f)
QObject::~QObject: Timers cannot be stopped from another thread
```
This happened while I was trying to write `(sphere 1)`, if that helps (I only got about as far as `(sp`)
When I try to launch it again, now it crashes instantly (even after rebooting) rather than giving me a few seconds of apparently working; here is the output of an instant crash:
```
hazel@hazel-VirtualBox:~/stuff/libfive/libfive/build/studio$ ./Studio
;;; note: auto-compilation is enabled, set GUILE_AUTO_COMPILE=0
;;;       or pass the --no-auto-compile argument to disable.
;;; compiling /usr/share/guile/site/2.2/libfive/kernel.scm
;;; WARNING: compilation of /usr/share/guile/site/2.2/libfive/kernel.scm failed:
;;; In procedure module-lookup: Unbound variable: with-exception-handler
guile: uncaught throw to unbound-variable: (#f Unbound variable: ~S (libfive-opcode-enum) #f)
QObject::~QObject: Timers cannot be stopped from another thread
```

**Comment by mkeeter** [comment]
After running `sudo make install`, you can run the application by just typing `studio` in any terminal (no capital letter, no leading `./`, don't need to be in the `build` dir).

This will run `/usr/local/bin/studio`, loading `/usr/local/lib/libfive.dylib` and the Scheme bindings from Guile's `(%site-dir)` (on my computer, it's `/usr/local/Cellar/guile/3.0.4/share/guile/site/3.0`, but yours will vary).

You _should_ also be able to double-click on the `Studio.desktop` file (and even copy it to your desktop) to launch the application, though that's untested.

Anyways, this specific error is because you're on Guile 2.2, rather than 3.0 – newer Guile adds `with-exception-handler` to replace old-style `catch`.  I've reverted to `catch` in 1ea5c48bc482b0fced2c4de16e78f37804287dc4 – can you see if that fixes it?

At some point, I'll want to bump the minimum Ubuntu version to 20.04, which includes Guile 3, but hopefully this is the only new Guile feature that I used by accident.

**Comment by omgitsraven** [comment]
1. OK: now instead of crashing, `(sphere 1)` did nothing for so long that I assumed that the program was broken, but eventually a sphere suddenly appeared.
The enormous delay seems to only happen on first launch (on my next launch a sphere appeared right after typing `(sphere 1)`) but even so, that was a strange enough period of time that I'd really recommend having a visible progress bar of some kind, rather than just leaving new users wondering why the program is unresponsive.

2.
```
hazel@hazel-VirtualBox:~$ studio
studio: command not found
```

3. Where is "the Studio.desktop file" that I'm meant to be double-clicking on

**Comment by smilberger** [comment]
I'm using Guile 3.0.4 on Ubuntu 18.04.1 and this build seems to be working for me, except for the desktop file.  I tried it with a couple sample models.

@omgitsraven The ```Studio.desktop``` file is in ./studio/deploy/linux.  

Unfortunately, clicking on it on my system (Ubuntu 18.04) gives me "Untrusted application launcher".  I did ```gio set Studio.desktop "metadata::trusted" yes```, this set icon to be a gear.  Double clicking on it then gave me "There was an error launching the application".  I put the full path to the new executable (upper case) in the "Exec" field, then double clicking it worked.  Apparently the lower case executable isn't getting installed.

**Comment by mkeeter** [comment]
Alright, I just pushed a fix for everything (hopefully 😛)

> OK: now instead of crashing, (sphere 1) did nothing for so long that I assumed that the program was broken, but eventually a sphere suddenly appeared.

Yup, that's because Guile had to compile all of the `scm` files.  I've now changed things around so that those files are compiled during the build, and the _compiled_ files are installed with `sudo make install`, so that should be fixed.

As @smilberger noted, the installed executable is actually named `Studio` rather than `studio`; apparently the `RENAME` directive is just silently ignored for binary targets 🤷🏻‍♂️ 

I've updated the `Studio.desktop` file [here](https://github.com/libfive/libfive/blob/pure-scheme-bindings/studio/deploy/linux/Studio.desktop) to match.  Not sure about the "Untrusted application launcher" issue, but there's plenty of discussion on the internet about fixing it by modifying owners or permissions.  I've given `Studio.desktop` execute privileges in the repo, but dunno if that's preserved when you download it and copy it around.

**Comment by smilberger** [comment]
I just read that the ```gio``` trust command I ran has to be done on reboot in some autostart file--it doesn't persist between reboots.  On the other hand, avoiding the use of a desktop file and compiling the binary as a fixed position executable makes it less secure because it can't be randomly relocated.  I'm planning on continuing to run the damn thing by supplying the full executable path in a terminal.  This has the benefit of showing any debug messages.

@mkeeter You might think about making the ```Studio.desktop``` file generated (if you are brave and keep using it), with the whole path for executable in the "Exec" field, in case a user has some older executable in a different path.

Overall, I don't know how much "trust" I put in file typing heuristics hacked on to a creaky 50 year old OS security model with some byzantine desktop security tacked on. (I personally think it's  just "security theater". :smile:)

**Comment by smilberger** [comment]
Apparently the Gnome desktop is (like emacs and systemd) an OS itself,
including a shadow file system with its own "convenience" layer [GIO](https://developer.gnome.org/gio/2.56/gvfs-overview.png).

After reading TFM and doing some testing myself, rather than just
believing the crowd at SO, I found out that apparently it would take a
Schrödinger quantum wave equation to model the persistence of the
trust metadata of the desktop file.  The answers delivered on SO,
etc., for the topics raised by #380 seem to a be look at the inner
workings of a quantum computer.

Of course now (I think Heisenberg continues to hold) this PR
is broken for me in a *different* way:

    o<|:o(` clive@marengo:~/support/libfive/build $ make -j2
    Scanning dependencies of target libfive-guile
    Scanning dependencies of target five-version
    [  0%] Generating libfive/kernel.go
    ;;; note: auto-compilation is enabled, set GUILE_AUTO_COMPILE=0
    ;;;       or pass the --no-auto-compile argument to disable.
    ;;; compiling /usr/local/bin/guild
    [  0%] Built target five-version
    [  1%] Generating libfive/lib.go
    ;;; note: auto-compilation is enabled, set GUILE_AUTO_COMPILE=0
    ;;;       or pass the --no-auto-compile argument to disable.
    ;;; compiling /usr/local/bin/guild
    ;;; compiled /home/clive/.cache/guile/ccache/3.0-LE-8-4.3/usr/local/bin/guild.go
    ;;; compiled /home/clive/.cache/guile/ccache/3.0-LE-8-4.3/usr/local/bin/guild.go
    wrote `/home/clive/.cache/guile/ccache/3.0-LE-8-4.3/home/clive/support/libfive/libfive/bind/guile/libfive/lib.scm.go'
    cp: cannot create regular file 'libfive/lib.go': No such file or directory
    libfive/bind/guile/CMakeFiles/libfive-guile.dir/build.make:73: recipe for target 'libfive/bind/guile/libfive/lib.go' failed
    make[2]: *** [libfive/bind/guile/libfive/lib.go] Error 1
    make[2]: *** Waiting for unfinished jobs....
    
    [...]
    
    [ 51%] Linking CXX shared library libfive.so
    [ 51%] Built target five
    Makefile:129: recipe for target 'all' failed

**Comment by mkeeter** [comment]
Can you add `VERBOSE=1` to show what commands are running?

On my machine, it automatically creates `build/libfive/bind/guile` before copying stuff into it.

**Comment by mkeeter** [comment]
(Also, this commit may fix it by using `cmake -E copy` instead of plain ol' `cp`)

**Comment by smilberger** [comment]
That commit seemed to help it get further, but still errs out with "Could not find libfive shared library":

```
[ 78%] Generating libfive/kernel.go
cd /home/clive/support/libfive/build/libfive/bind/guile && guild compile -L/home/clive/support/libfive/libfive/bind/guile /home/clive/support/libfive/libfive/bind/guile/libfive/kernel.scm
Backtrace:
In ice-9/psyntax.scm:
  1241:36 19 (expand-top-sequence ((use-modules (oop goops) (# …) …)) …)
  1233:19 18 (parse _ (("placeholder" placeholder)) ((top) #(# # …)) …)
   285:10 17 (parse _ (("placeholder" placeholder)) (()) _ c&e (# #) #)
In ice-9/boot-9.scm:
  3898:20 16 (process-use-modules _)
   222:29 15 (map1 (((oop goops)) ((rnrs bytevectors)) ((srfi #)) # …))
   222:29 14 (map1 (((rnrs bytevectors)) ((srfi srfi-28)) ((# #)) # …))
   222:29 13 (map1 (((srfi srfi-28)) ((system foreign)) ((# lib)) #))
   222:29 12 (map1 (((system foreign)) ((libfive lib)) ((libfive …))))
   222:17 11 (map1 (((libfive lib)) ((libfive vec))))
  3899:31 10 (_ ((libfive lib)))
  3297:17  9 (resolve-interface (libfive lib) #:select _ #:hide _ # _ …)
In ice-9/threads.scm:
    390:8  8 (_ _)
In ice-9/boot-9.scm:
  3223:13  7 (_)
In ice-9/threads.scm:
    390:8  6 (_ _)
In ice-9/boot-9.scm:
  3507:20  5 (_)
   2806:4  4 (save-module-excursion #<procedure 55662e9ca1e0 at ice-…>)
  3527:26  3 (_)
In unknown file:
           2 (primitive-load-path "libfive/lib" #<procedure 55662e9d…>)
In ice-9/boot-9.scm:
   1991:7  1 (error _ . _)
  1669:16  0 (raise-exception _ #:continuable? _)

ice-9/boot-9.scm:1669:16: In procedure raise-exception:
Could not find libfive shared library
libfive/bind/guile/CMakeFiles/libfive-guile.dir/build.make:68: recipe for target 'libfive/bind/guile/libfive/kernel.go' failed
make[2]: *** [libfive/bind/guile/libfive/kernel.go] Error 1
make[2]: Leaving directory '/home/clive/support/libfive/build'
CMakeFiles/Makefile2:310: recipe for target 'libfive/bind/guile/CMakeFiles/libfive-guile.dir/all' failed
make[1]: *** [libfive/bind/guile/CMakeFiles/libfive-guile.dir/all] Error 2
make[1]: Leaving directory '/home/clive/support/libfive/build'
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by smilberger** [comment]
By the way, I removed all installed versions of 'libfive.so" in the LD_LIBRARY_PATH, if that helps.

**Comment by mkeeter** [comment]
Aha, building some of the `.scm` files actually depends on `libfive.dylib`; mine was using the installed library, so I didn't notice.  I've added dependencies and tweaked the search path yet again, so that it finds the shared library when pre-compiling the SCM files.

**Comment by smilberger** [comment]
For future reference, in case someone else reports it later, I've gotten this message twice today, with various effects like SIGTERMing my browser, desktop manager, and/or locking up my whole laptop, followed by the compiler (why the compiler isn't first, I don't know):

```[ 25%] Building CXX object libfive/src/CMakeFiles/five.dir/render/brep/hybrid/hybrid_tree2.cpp.o
[ 26%] Building CXX object libfive/src/CMakeFiles/five.dir/render/brep/hybrid/hybrid_tree3.cpp.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
libfive/src/CMakeFiles/five.dir/build.make:902: recipe for target 'libfive/src/CMakeFiles/five.dir/render/brep/hybrid/hybrid_tree2.cpp.o' failed
make[2]: *** [libfive/src/CMakeFiles/five.dir/render/brep/hybrid/hybrid_tree2.cpp.o] Error 4
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:113: recipe for target 'libfive/src/CMakeFiles/five.dir/all' failed
make[1]: *** [libfive/src/CMakeFiles/five.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2```

I suspect it is C++ template metaprogramming magic (Eigen?) gone awry (memory exhaustion?).  To fix it, I just reboot to no-X mode, and run it as a single job.  My pleas to add Lisp-style macros to C++ for compile time programming have largely been ignored by Dr. Stroustrup. :)  Joking aside, thank *you*.  I know you put an incalculable amount of time into this project yourself!

**Comment by smilberger** [comment]
Cool, commit be6d403 seemed have fixed it.  It does (and I'm a little hesitant to say this for fear of old Heisenberg) compile the Guile code only after running Studio the first time.

By the way, to be fair to g++, after a day of looking at HN and lobste.rs articles about the good old days when computers were much simpler tends to load up a lot of JavaScript, so that may have contributed to the memory exhaustion thing.

**Comment by smilberger** [comment]
More good news, I wiped everything installed by LIbfive (there were a lot of Scheme files in various places).  After that, I rebuilt from scratch--the Guile code compiled during the build as expected, and Studio was ready to render on startup.

**Comment by mkeeter** [comment]
Great – I made one more tweak, but think that I checked everything this time.  @omgitsraven , want to take a look on your VM?

(@smilberger – In case you're curious, I think your suspicions about memory exhaustion are correct.  `hybrid_tree2/3.cpp` are doing some [fancy template metaprogramming](https://github.com/libfive/libfive/blob/master/libfive/src/render/brep/hybrid/hybrid_tree.inl#L592) to statically unroll a bunch of 1/2/3-D matrix calculations, so that **all matrix sizes** are known at compile-time and Eigen can generate better code, but it's... not easy on the compiler).

**Comment by smilberger** [comment]
@mkeeter Conway's "Game of Life" is [turing complete](https://codegolf.stackexchange.com/questions/88783/build-a-digital-clock-in-conways-game-of-life#answers) 😲 too--but I wouldn't implement a linear alg. library in it.  

But (with respect to Gnome, Eigen, etc.):

“There are only two kinds of languages: the ones people complain about and the ones nobody uses.” -- Stroustrup
"Democracy is the worst form of Government except for all those other forms..." -- Churchill

Try finding something like Eigen in C or Rust...

**Comment by omgitsraven** [comment]
Everything seems to be working for me! I had to say I trust the launcher on first launch, but it hasn't prompted me again since; I can still only launch it from the Terminal with `Studio` rather than `studio`, but that doesn't make a difference to me... and, it can `(sphere 1)` without crashing :) (More complex files seem to load fine too, at a glance.)

**Comment by mkeeter** [comment]
Great, let's bring it in!

**Comment by smilberger** [comment]
> I had to say I trust the launcher on first launch, but it hasn't prompted me again since

It's always good to see Schrödenger's cat come out alive, of course.

       _____
      |     |
      |     |
      |     |
             \
              \

:cat2:

**Pull request merged**
