### PR TITLE
WIP: Cmake export

### PR DESCRIPTION
**Pull request by kayarre**
I modified the cmake build process to be able to generate the Config.cmake files needed in order to use find_package

I made a lot of rookie mistakes, but I was able to get it working. It would be great to have someone give it a good look through.

Also I didn't make a clean branch from my other pull request, if someone can tell me the magic git  commands  to fix that, cherry pick?

### CODE REVIEW

**Comment by FunMiles** [comment]
@kayarre I am going to look at your CMake changes. Meanwhile, what you want to do can be trivially achieved with an interactive rebase. You can do an interactive rebase and move the last commit up by three. There will not be any conflict. Then move the head of this branch to that commit.
I am not sure if you can force push the result for the PR. If not, you can create a new branch at that commit and submit that.

**Comment by FunMiles** [comment]
@kayarre Your PR does not seem to work in an out-of-source build. Can you try to check it out somewhere fresh, then create a sibling directory and try to build it in there? I get:

> michel@Michels-MacBook-Pro build % make -j 16
Scanning dependencies of target five-version
/bin/sh: line 0: cd: /Users/michel/Development/OpenSource/CAD/LibFive/build/libfive/src: No such file or directory
make[2]: *** [libfive/CMakeFiles/five-version] Error 1
make[1]: *** [libfive/CMakeFiles/five-version.dir/all] Error 2
make: *** [all] Error 2

**Comment by FunMiles** [comment]
My complete set of fixes are here:

https://github.com/FunMiles/libfive/tree/cmake_export

I can create a PR from that but I want to make sure you get credit for doing the biggest part.

**Comment by mkeeter** [comment]
I'm hesitant to merge this in because (in my experience), this kind of infrastructure change ends up bit-rotting through disuse unless a core maintainer is using it *often*.

For example, `libfive` has a [Travis config](https://github.com/libfive/libfive/blob/master/.travis.yml) and a [Docker image](https://github.com/libfive/libfive/blob/master/Dockerfile) right now, both of which are (probably) broken, because there's no one that's using them regularly.

I'd be happy to leave this PR open and perhaps link to it in the README (for example, as `Dear ImGui` does with unstable features), but don't necessarily want to take responsibility for maintaining it in `master`.

**Comment by FunMiles** [comment]
I am likely to be using libfive in the long run. I don't mind maintaining it.
My point of view is that if you use CMake, you should do everything uses of cmake implies.
As mentioned, I've also updated finding the include directory for Eigen. Using the variable is not the modern way.
A few years back, I would have said that creating support for `find_package` was for experts only, but modern CMake (>3.10 ??) has made it easier.

**Comment by FunMiles** [comment]
I have decided to make a more complete new PR with a namespace so that the use is with `LibFive::core`

**Comment by kayarre** [comment]
@mkeeter I would say that updating the cmake is inhibiting bit rot, and can lower the bar to entry for others. i.e. I have done most of this learning the hard way not being a formally trained software developer, as well as I have learned how to do things a certain (imperfect) way, and  have a lot of work to do to develop the mental models missing of compilation, and linking work. It is hard for me to know when I can afford the time for a new mental model or want something that works with less friction.  I acknowledge the hesitancy. thank you for being willing to look at it.

@FunMiles  Thank you for picking this up and fixing the issues. I happy with whatever in terms of the merge request. I will close this if your merge request is ready.

**Comment by FunMiles** [comment]
I have made a PR https://github.com/libfive/libfive/pull/353 with my cleaned up changes. I've also added an explanation on how to use the library from a CMake project. I hope it is clear and useful.

**Pull request closed without merging**
