### PR TITLE
Python bindings (!!)

### PR DESCRIPTION
**Pull request by mkeeter**
This PR adds Python bindings, with the usual mix of hand-written wrappers for a `Shape` class and an autogenerated standard library.

It bumps CMake to 3.12, which is required to use `find_package(Python3...)`.  This is included in the latest Ubuntu LTS, though not in 18.04, so we'll have to update the build instructions again.

### CODE REVIEW

**Comment by omgitsraven** [comment]
Whoa!!

How does this work exactly -- does Studio support it?
And if so... does that mean that Studio could build on Windows, in Python mode rather than Scheme mode?

**Comment by mkeeter** [comment]
Right now, this is just the command-line bindings – here's what it looks like running in IPython and a [separate mesh viewer](https://github.com/mkeeter/erizo):
Screen Shot 2021-03-04 at 1 04 48 PM

The plan is to build this into Studio, but that's a few PRs away – the current architecture is tightly coupled to Scheme being the language, so I'll have to pull that into an abstraction first.  Once that's done, a Windows build will be theoretically possible!

**Comment by omgitsraven** [comment]
Exciting times!! In the meantime maybe I'll give that command-line version a shot on Windows sometime soon...

**Comment by mkeeter** [comment]
Updated and (probably) good to go; if this breaks anything, we can fix it in post.

**Pull request merged**
