### PR TITLE
Build Studio GUI on Windows

### PR DESCRIPTION
**Pull request by mkeeter**
This PR adds instructions for building + running the Studio GUI on Windows, using [MSYS2](https://www.msys2.org/) to install dependencies and toolchains.

I tested in a VM without OpenGL 3 support, so I couldn't test everything, but after manually disabling the 3D `View`, it seems to run:

Screen Shot 2021-03-15 at 3 45 07 PM

@omgitsraven – want to test this out?

### CODE REVIEW

**Comment by mkeeter** [comment]
@craftyjon is now trying to build with VS2019 + `vcpkg` instead, which has all of the required packages and would be a bit cleaner than using MSYS2!  🤞🏻

**Comment by omgitsraven** [comment]
Gladly!! :)

So close; it builds most of the targets correctly, but chokes on Studio_autogen:
```
Hazel@DESKTOP-D5NADQI MINGW64 ~/libfive/build
$ make -j8
[  6%] Built target libfive-python
[  6%] Built target five-version
[ 54%] Built target five
[ 56%] Built target five-stdlib
[ 57%] Building CXX object libfive/test/CMakeFiles/libfive-test.dir/api.cpp.obj
[ 58%] Building CXX object libfive/test/CMakeFiles/libfive-test.dir/eval_deriv_array.cpp.obj
[ 59%] Building CXX object libfive/test/CMakeFiles/libfive-test.dir/eval_feature.cpp.obj
[ 59%] Building CXX object libfive/test/CMakeFiles/libfive-test.dir/feature.cpp.obj
[ 60%] Building CXX object libfive/test/CMakeFiles/libfive-test.dir/heightmap.cpp.obj
[ 61%] Building CXX object libfive/test/CMakeFiles/libfive-test.dir/hybrid_meshing.cpp.obj
[ 61%] Building CXX object libfive/test/CMakeFiles/libfive-test.dir/indexes.cpp.obj
[ 62%] Automatic MOC and UIC for target Studio
[ 62%] Built target Studio_autogen
[ 63%] Building CXX object studio/CMakeFiles/Studio.dir/src/python/interpreter.cpp.obj
[ 64%] Building CXX object libfive/test/CMakeFiles/libfive-test.dir/marching.cpp.obj
[ 65%] Building CXX object libfive/test/CMakeFiles/libfive-test.dir/manifold_tables.cpp.obj
[ 65%] Building CXX object libfive/test/CMakeFiles/libfive-test.dir/mesh.cpp.obj
[ 66%] Building CXX object libfive/test/CMakeFiles/libfive-test.dir/neighbors.cpp.obj
In file included from C:/msys64/home/Hazel/libfive/libfive/test/api.cpp:13:
C:/msys64/home/Hazel/libfive/libfive/test/catch.hpp: In instantiation of 'bool Catch::compareEqual(const LhsT&, const RhsT&) [with LhsT = const libfive::TreeData*; RhsT = long long int]':
C:/msys64/home/Hazel/libfive/libfive/test/catch.hpp:1413:34:   required from 'const Catch::BinaryExpr<LhsT, const RhsT&> Catch::ExprLhs<LhsT>::operator==(const RhsT&) [with RhsT = long long int; LhsT = const libfive::TreeData* const&]'
C:/msys64/home/Hazel/libfive/libfive/test/api.cpp:219:5:   required from here
C:/msys64/home/Hazel/libfive/libfive/test/catch.hpp:1384:98: error: ISO C++ forbids comparison between pointer and integer [-fpermissive]
 1384 |     auto compareEqual( LhsT const& lhs, RhsT const& rhs ) -> bool { return static_cast<bool>(lhs == rhs); }
      |                                                                                              ~~~~^~~~~~
C:/msys64/home/Hazel/libfive/libfive/test/catch.hpp: In instantiation of 'bool Catch::compareNotEqual(const LhsT&, RhsT&&) [with LhsT = const libfive::TreeData*; RhsT = const long long int&]':
C:/msys64/home/Hazel/libfive/libfive/test/catch.hpp:1421:37:   required from 'const Catch::BinaryExpr<LhsT, const RhsT&> Catch::ExprLhs<LhsT>::operator!=(const RhsT&) [with RhsT = long long int; LhsT = const libfive::TreeData* const&]'
C:/msys64/home/Hazel/libfive/libfive/test/api.cpp:222:5:   required from here
C:/msys64/home/Hazel/libfive/libfive/test/catch.hpp:1395:96: error: ISO C++ forbids comparison between pointer and integer [-fpermissive]
 1395 |     auto compareNotEqual( LhsT const& lhs, RhsT&& rhs ) -> bool { return static_cast<bool>(lhs != rhs); }
      |                                                                                            ~~~~^~~~~~
make[2]: *** [libfive/test/CMakeFiles/libfive-test.dir/build.make:95: libfive/test/CMakeFiles/libfive-test.dir/api.cpp.obj] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from C:/msys64/mingw64/x86_64-w64-mingw32/include/windows.h:71,
                 from C:/msys64/mingw64/include/QtCore/qt_windows.h:64,
                 from C:/msys64/mingw64/include/QtGui/qopengl.h:49,
                 from C:/msys64/mingw64/include/QtGui/qopenglvertexarrayobject.h:48,
                 from C:/msys64/mingw64/include/QtGui/QOpenGLVertexArrayObject:1,
                 from C:/msys64/home/Hazel/libfive/studio/include/studio/shape.hpp:23,
                 from C:/msys64/home/Hazel/libfive/studio/src/python/interpreter.cpp:24:
C:/msys64/home/Hazel/libfive/studio/src/python/interpreter.cpp:90:22: error: expected unqualified-id before numeric constant
   90 | const static QString SET_BOUNDS = "studio.set_bounds([%1, %2, %3], [%4, %5, %6])\n";
      |                      ^~~~~~~~~~
C:/msys64/home/Hazel/libfive/studio/src/python/interpreter.cpp: In member function 'virtual QString Studio::Python::Interpreter::defaultScript()':
C:/msys64/home/Hazel/libfive/studio/src/python/interpreter.cpp:109:20: error: request for member 'arg' in '4109', which is of non-class type 'int'
  109 |         SET_BOUNDS.arg(default_settings.min.x())
      |                    ^~~
C:/msys64/home/Hazel/libfive/studio/src/python/interpreter.cpp: In member function 'virtual void Studio::Python::Interpreter::eval(QString)':
C:/msys64/home/Hazel/libfive/studio/src/python/interpreter.cpp:376:32: error: request for member 'arg' in '4109', which is of non-class type 'int'
  376 |                     SET_BOUNDS.arg(out.settings.min.x())
      |                                ^~~
C:/msys64/home/Hazel/libfive/studio/src/python/interpreter.cpp:381:58: error: no matching function for call to 'QList<QPair<QString, QString> >::append(<brace-enclosed initializer list>)'
  381 |                               .arg(out.settings.max.z())});
      |                                                          ^
In file included from C:/msys64/mingw64/include/QtCore/qobject.h:49,
                 from C:/msys64/mingw64/include/QtCore/qcoreapplication.h:46,
                 from C:/msys64/mingw64/include/QtWidgets/qapplication.h:44,
                 from C:/msys64/mingw64/include/QtWidgets/QApplication:1,
                 from C:/msys64/home/Hazel/libfive/studio/src/python/interpreter.cpp:20:
C:/msys64/mingw64/include/QtCore/qlist.h:620:27: note: candidate: 'void QList<T>::append(const T&) [with T = QPair<QString, QString>]'
  620 | Q_OUTOFLINE_TEMPLATE void QList<T>::append(const T &t)
      |                           ^~~~~~~~
C:/msys64/mingw64/include/QtCore/qlist.h:620:53: note:   no known conversion for argument 1 from '<brace-enclosed initializer list>' to 'const QPair<QString, QString>&'
  620 | Q_OUTOFLINE_TEMPLATE void QList<T>::append(const T &t)
      |                                            ~~~~~~~~~^
C:/msys64/mingw64/include/QtCore/qlist.h:1018:13: note: candidate: 'void QList<T>::append(const QList<T>&) [with T = QPair<QString, QString>]'
 1018 | inline void QList<T>::append(const QList<T> &t)
      |             ^~~~~~~~
C:/msys64/mingw64/include/QtCore/qlist.h:1018:46: note:   no known conversion for argument 1 from '<brace-enclosed initializer list>' to
const QList<QPair<QString, QString> >&'
 1018 | inline void QList<T>::append(const QList<T> &t)
      |                              ~~~~~~~~~~~~~~~~^
make[2]: *** [studio/CMakeFiles/Studio.dir/build.make:380: studio/CMakeFiles/Studio.dir/src/python/interpreter.cpp.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:354: studio/CMakeFiles/Studio.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:298: libfive/test/CMakeFiles/libfive-test.dir/all] Error 2
make: *** [Makefile:103: all] Error 2
```

**Comment by mkeeter** [comment]
Are you on the `windows-gui` branch?  Those all look familiar, and I think I've fixed them already.

**Comment by omgitsraven** [comment]
Oh my goodness, you're right, I'm not. Totally slipped my mind that this was a branch. One moment.

**Comment by craftyjon** [comment]
Got this working on VS2019, in Release mode at least

1) Install packages

`.\vcpkg.exe install eigen3 boost libpng qt5 python3`

2) Set up VS2019

- File > Open > CMake... and pick CMakeLists.txt
- Create a Release or RelWithDebInfo target using Project > CMake Settings for libfive
- Debug > Debug and Launch Settings for Studio > Put the following in launch.vs.json for the Studio target:

```
"env": {
    "PYTHONHOME": "C:\\<path>\\<to>\\vcpkg\\installed\\x64-windows\\tools\\python3",
    "PYTHONPATH": "C:\\<path>\\<to>\\libfive\\out\\build\\x64-Release\\libfive\\bind\\python",
    "LIBFIVE_FRAMEWORK_DIR": "C:\\<path>\\<to>\\libfive\\out\\build\\x64-Release"
}
```

3) Patch `libfive\bind\python\libfive\ffi.py` to look for "five.dll" instead of "libfive.dll" unless Matt has fixed this already

4) Build!

5) Copy five.dll and five-stdlib.dll from `libfive\out\build\x64-Release\libfive\src` and `libfive\out\build\x64-Release\libfive\stdlib` to `libfive\out\build\x64-Release\studio` (a cmake install target for Studio could probably remove this requirement)

Note: I wasn't able to get Debug running, I suspect because vcpkg Python doesn't include the debug binaries but I'm not certain of this.  I think there is a way to get vcpkg to install the Python debug binaries as well as the release binaries but I don't have time to investigate that further at the moment.

image

**Comment by omgitsraven** [comment]
well, my method might be obsolete by now, but all the same: it built correctly, but running gives me this:
```
Hazel@DESKTOP-D5NADQI MINGW64 ~/libfive/build
$ PYTHONHOME=/mingw64 ./studio/Studio.exe
C:/msys64/home/Hazel/libfive/build/studio/Studio.exe: error while loading shared libraries: libfive.dll: cannot open shared object file: No such file or directory
```

**Comment by omgitsraven** [comment]
I tried changing directories, and it got weirder:
```
Hazel@DESKTOP-D5NADQI MINGW64 ~/libfive/build/studio
$ PYTHONHOME=/mingw64 ./Studio.exe
C:/msys64/home/Hazel/libfive/build/studio/Studio.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory
```

**Comment by craftyjon** [comment]
> 
> 
> well, my method might be obsolete by now, but all the same: it built correctly, but running gives me this:
> 
> ```
> Hazel@DESKTOP-D5NADQI MINGW64 ~/libfive/build
> $ PYTHONHOME=/mingw64 ./studio/Studio.exe
> C:/msys64/home/Hazel/libfive/build/studio/Studio.exe: error while loading shared libraries: libfive.dll: cannot open shared object file: No such file or directory
> ```

See step 3 in my notes above -- it's looking for `libfive.dll` instead of `five.dll` which is the Windows naming convention created by cmake

in `ffi.py` around line 19 make it look like:

```
    elif sys.platform == "win32":
        suffix = '.dll'
        name = name.replace('lib', '')
```

**Comment by mkeeter** [comment]
Hmmm, it should work from the `build` directory, but you have to manually copy `libfive.dll` into the Studio subfolder:
``` cp libfive/src/libfive.dll studio```

**Comment by mkeeter** [comment]
This commit ⬆️ should remove the need for Windows-specific hacks in `ffi.py`, by always producing `libfive.{dylib,so,dll}` on all platforms.  I'll test out VS2019 tomorrow and make sure that Jon's instructions work for me – if that works, then I think it's preferable to MSYS2, since it's a more common Windows toolchain.

**Comment by omgitsraven** [comment]
Yep I already did `cp libfive/src/libfive.dll studio`:
image

btw, I tried double-clicking Studio.exe directly, and it gave me what might be a more detailed error message (although it might be related to opening without setting PYTHONHOME of course):
image

**Comment by craftyjon** [comment]
I also found that in Studio's `APP::APP`, the `LIBFIVE_FRAMEWORK_DIR` is overwritten and forced to something that looks kind of irrelevant on Windows, which prevents that env var actually being useful for running Studio (I guess I had that left over from testing the Python module standalone)

**Comment by craftyjon** [comment]
Oh I also forgot to mention in my instructions above that the `find_package(Qt5Core 5.12)` needs to be moved out of the conditional so that it runs under MSVC as well as non-MSVC

**Comment by mkeeter** [comment]
> ```
>C:/msys64/home/Hazel/libfive/build/studio/Studio.exe: error while loading shared libraries: libfive.dll: cannot open shared object file: No such file or directory
> ```
I'm not sure about this error message!  You can install [`ntlld`](https://packages.msys2.org/package/mingw-w64-x86_64-ntldd) and run it on `studio/Studio.exe` to see what it's looking for, but I didn't run into issues finding `libfive.dll`, when it was copied into the same folder as `Studio.exe`.

Alternatively, try out the VS2019 instructions and see if those work more smoothly!

**Comment by mkeeter** [comment]
@omgitsraven – I believe the [latest instructions](https://github.com/libfive/libfive/blob/windows-gui/README.md#windows-vs2019) should now work using the VS2019 toolchain!

You should undo the `Path` modifications, so things don't find MSYS2 binaries and get confused.  (I actually uninstalled MSYS2 entirely, using the Add/Remove Programs dialog).

**Comment by omgitsraven** [comment]
At last!!!
image

**Pull request merged**
