### PR TITLE
Build on Apple Silicon 

### PR DESCRIPTION
**Pull request by andreypopp**
See #415

This addresses all but Boost error described in the related issue.

Not a cpp/cmake expert here but hopefully what I've done makes sense. I am building with Python and without Guile and the studio app works.

### CODE REVIEW

**Comment by andreypopp** [comment]
Tests output, fails on mesh with SIGSEGV:
```
; ./build/libfive/test/libfive-test

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libfive-test is a Catch v2.13.4 host application.
Run with -? for options

-------------------------------------------------------------------------------
Heightmap::render: Performance
-------------------------------------------------------------------------------
../libfive/test/heightmap.cpp:259
...............................................................................

benchmark name                       samples       iterations    estimated
                                     mean          low mean      high mean
                                     std dev       low std dev   high std dev
-------------------------------------------------------------------------------
sphere                                         100             1     3.58099 s
                                        36.2117 ms    35.8977 ms    36.5944 ms
                                        1.75265 ms    1.45071 ms    2.12202 ms

Menger sponge                                  100             1     13.9412 s
                                        139.873 ms     139.33 ms    140.529 ms
                                        3.03117 ms    2.54404 ms    3.79862 ms


-------------------------------------------------------------------------------
Mesh::render (cone)
-------------------------------------------------------------------------------
../libfive/test/mesh.cpp:123
...............................................................................

../libfive/test/mesh.cpp:123: FAILED:
due to a fatal error condition:
  SIGSEGV - Segmentation violation signal

===============================================================================
test cases:     78 |     77 passed | 1 failed
assertions: 559241 | 559240 passed | 1 failed

zsh: segmentation fault  ./build/libfive/test/libfive-test
```

**Comment by andreypopp** [comment]
Ok, the latest commit fixes the issue. I'm entirely sure if 8 is the correct value here though. Tests now pass.

**Comment by mkeeter** [comment]
Thanks, I'll check it out!

According to the [Eigen docs](http://eigen.tuxfamily.org/index.php?title=FAQ#What_can.27t_be_vectorized.3F), NEON has a packet size of 16 bytes, which is a SIMD size of 4 (rather than 8).

**Comment by andreypopp** [comment]
> According to the Eigen docs, NEON has a packet size of 16 bytes, which is a SIMD size of 4 (rather than 8).

Oh, yeah, missed that. Fixed.

**Comment by mkeeter** [comment]
I finally got an M1 Mac, so using this PR as a reference, got this working in d587b433329ada5586b2150ac5ea0dc1fe1f0a3c (this also involved updating to Qt 6, since that's what Homebrew is installing by default now!)

Thanks!

**Pull request closed without merging**
