### PR TITLE
[FEAT] improved text editor indentation

### PR DESCRIPTION
**Pull request by SGSSGene**
This improves the indentation as described in #70 
The following example can be written without hitting space or tab once.
```
(add 12 23
     34 45 (minus
                  56
                  67)
     17)
```

### CODE REVIEW

**Comment by smilberger** [comment]
Thanks, this is nice!

[These](https://dept-info.labri.fr/~strandh/Teaching/PFS/Common/Strandh-Tutorial/indentation.html) are some conventions for Lisp indentation.  Scheme has slightly different conventions, Emacs is a good editor to check as it has a Scheme mode.

**Comment by SGSSGene** [comment]
> Thanks, this is nice!
> 
> [These](https://dept-info.labri.fr/~strandh/Teaching/PFS/Common/Strandh-Tutorial/indentation.html) are some conventions for Lisp indentation. Scheme has slightly different conventions, Emacs is a good editor to check as it has a Scheme mode.

Oh, cool very nice. I will adjust it accordingly!

**Comment by smilberger** [comment]
> Do you know hat is different between lisp and scheme indentation?

Mostly Common Lisp are indented the same in spirit, despite their syntactic differences.

```
(defun f (x)
  (* x 3))
```
Scheme would be:

```
(define (f x)
  (* x 3)
```
I wouldn't worry about it, but just be aware when reading Common Lisp formatting guidelines like the one I mentioned.

> What do you think about this guideline?

It's a good reference.  (It taught me that parens get lonely. 😢 The trailing whitespace in their examples, I would avoid.)  Even among Scheme implementations, there are small variations in convention.  Emacs has "sub-modes" for indentation depending on whether you are using Guile, MIT Scheme, etc.  If I was going to do a big enough model for any of this to make a difference I would probably use an external editor.  I can autoindent a whole file at a time in Emacs, and tweak it to my personal preferences.

That said, I'm not sure either of these documents addressed comments enough.  Roughly (I don't have a reference):

1) One semicolon is used as a trailing style comment, formatted like this (autoindenting mostly leaves these alone):

```
(define (f x) ; my function
```

2) Two semicolons are used for block matched comments (autoindented to the appropriate block indentation):

```
(define (f x)
  ;; this function is pointless, but O(1)!
  (* x 1))
```

3) 3 or more semicolons are used for top-level comments (autoindenting mostly leaves these alone)

```
;;; TODO: this function is O(3^n), do some loop unrolling?
(define (f x)
```
I don't use VIM at all, so someone else would have to tell you the specifics for that program.  Even [Google](https://google.github.io/styleguide/lispguide.xml#Formatting) defers to Emacs for their formatting guidelines:

> Indent your code the way a properly configured GNU Emacs does.

**Comment by omgitsraven** [comment]
I'm a little curious how mandatory this would be, because, I have my own I guess idiosyncratic style for it, based on how I'm used to writing curly-brace languages, stuff like

```
(sequence
	(sphere 1)
	(scale-xyz #[2 1 1])
	(union
		(difference
			(box-centered #[0.5 0.5 2])
			(cylinder 2 0.2)
		)
	)
	(rotate-x (/ pi 2))
)
```

but honestly, I was never totally convinced it was the most readable approach in general; I'd be willing to learn a more traditional style if people tend to not have issues once they're used to it...

**Comment by smilberger** [comment]
There is a little more contrast in the block level in @omgitsraven 's example, plus less "walls of parens" as opposed to what Google and Emacs demand:

```
(sequence
 (sphere 1)
 (scale-xyz #[2 1 1])
 (union
  (difference
   (box-centered #[0.5 0.5 2])
   (cylinder 2 0.2)))
 (rotate-x (/ pi 2)))
```

I personally don't use it enough to care, plus I'm hardly in any position to make anything mandatory. :smile:  At least the decision can be more informed now.  Can make a ```M-x omgitsraven-mode```?  Editor wars are almost as scary as language wars, maybe scarier.  Peace, out.

**Comment by SGSSGene** [comment]
Quote: "Oh no ... Oh no ... Oh no no no no no no".
What have I done? Why didn't I see that this task is a trap? ;-)

I think what we need first some permanent settings for studio. We need that also for other stuff like "rendering option, visible axis" etc. That could also allow to set activated/deactivated smart indentation.

I currently tend to use an external editor and use the auto reload function, which would also be cool to be a permanent setting

**Comment by mkeeter** [comment]
I'd support merging in this PR as an improvement to the status quo (since @omgitsraven style required manually indenting already, this isn't particularly worse), then revisiting once we have persistent settings in place.

I'll test it out locally in the next few days and make sure it looks good before merging!

**Comment by mkeeter** [comment]
Merged, thanks! 

(I ended up making a few more changes in 6be8af6175e9e6013f7509cc47c006eca86786bb to handle a wider variety of cases, but this was very helpful)

**Pull request merged**
