### PR TITLE
Add blend-clearance-inset

### PR DESCRIPTION
**Pull request by omgitsraven**
This is a function I like, to insert a shape into the surface of another one, with a smooth bevel surrounding it, as though pressing a marble partway into soft clay.

I'm admittedly unsure about whether this is getting too specific for a general CSG library, or whether you'd like to offer as much to the user as possible? (I'm also not certain whether its usage would be obvious just from reading it, especially with this name. Maybe "dimple inset"?)

### CODE REVIEW

**Comment by omgitsraven** [comment]
fyi I'm having second thoughts about automatically including `b` -- it's handy if you use it alone, but it gets in the way of nesting them

**Comment by omgitsraven** [comment]
Just realised a `union` rather than a `values` would work, at the expense of fusing together the surfaces as far as the bounding box optimization is concerned. I'm not sure if that would be too big a tradeoff to merit saving a bit of typing. (Though a fair bit of typing, if the shape wasn't already defined as a function.) I don't suppose there's any way to have a shape generated inside a function, but *not* passed back to the function that called it? So subsequent operations would apply to the "main" shape, but not the incidental ones that were created elsewhere in the function?

Admittedly, I'm not sure this function merits this much consideration, as it was just created to save time. Let me know if you think I should just forget it.

(I am thinking about adding `o` as an optional extra parameter to `blend-difference` however, since it seems like a fairly common use case, that wouldn't complicate anything... but people can always just do the `offset` right in the arguments themselves I guess.)

**Comment by mkeeter** [comment]
Yeah, I think this is a bit too niche – adding an optional parameter to `blend-difference` makes more sense to me.

Addressing your earlier comment, I think the standard library should avoid returning `values` lists, because stdlib functions don't usually take them as inputs – you could imagine doing `(move (blend-clearance-inset ...) ...)`, and it wouldn't behave correctly.

**Comment by omgitsraven** [comment]
Yeah, that's exactly the problem I ran into almost immediately. Alright, I'll add the optional parameter to `blend-difference`, and people can just define their `b` shape as a function, and pass it there then also place it afterwards. Thanks for the feedback!

**Pull request closed without merging**
