### PR TITLE
Add support MSVC+vcpkg in CMake.

### PR DESCRIPTION
**Pull request by speps**
This allows to create a libfive.sln file which compiles libfive-test correctly. There are still a few changes necessary (like automatically copying five.dll to libfive-test.exe folder).

### CODE REVIEW

**Comment by mkeeter** [comment]
Thanks!  I've rebased this onto `master` and done a bit of minor formatting tweaks.

Can you confirm that my [`speps-master` branch](https://github.com/libfive/libfive/tree/speps-master) still works as intended?

**Comment by mkeeter** [comment]
@speps I've merged this now to keep it from getting too far behind; feel free to ping me if my changes are subtly different from what you wanted.

**Comment by Yitzi2** [comment]
@speps In Visual Studio, _MSC_VER seems to be defined even when building it as a static library (and thus we don't want to import or export dll's).  Am I missing something, or does it need to have an option to build as a static library when _MSC_VER is defined as well?

**Comment by speps** [comment]
The `__declspec` doesn't matter if you're building a static library. If you want to build as a static library, you'll need to modify `src\CMakeLists.txt` to have STATIC instead of SHARED. It's easier to build as a shared library for `libfive` though as it has some tricky dependencies like boost and eigen3.

**Pull request closed without merging**
